// <auto-generated />
using System;
using KiAcorp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACorp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009014115_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KiAcorp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AesNik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AesPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AesPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesNik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DesPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DesPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rc4Nik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rc4Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rc4PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
